version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    groups:
      eslint:
        patterns:
          - "*eslint*"
      # group all dev dependencies that did not match so far
      dev-dependencies:
        dependency-type: "development"
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
    groups:
      laravel:
        patterns:
          - "laravel/*"
      linters:
        patterns:
          - "rector/rector"
          - "vimeo/psalm"
      prod-dependencies:
        dependency-type: "production"
      dev-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "rector/rector"
          - "vimeo/psalm"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 20
