build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run
                    - js-scrutinizer-run
        tests: false

filter:
    paths:
        - "app/"

checks:
    php: true
    javascript: true

coding_style:
    php: {  }

tools:
    external_code_coverage:
        timeout: 600
        runs: 2
