build:
    environment:
        php: 8.0.2
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]

filter:
    paths:
        - "app/"

checks:
    php: true

tools:
    external_code_coverage:
        timeout: 600
        runs: 1
