build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run

filter:
    paths:
        - "app/"

checks:
    php: true

coding_style:
    php: {  }

tools:
    external_code_coverage:
        timeout: 600
        runs: 2
