dist: xenial
language: php

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=false
    - APP_KEY=01234567890123456789012346579012
    - DB_CONNECTION=mysql
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_DATABASE=homestead
    - DB_USERNAME=travis
    - DB_PASSWORD=
    - LOG_CHANNEL=single
    - BUGSNAG_API_KEY=

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

cache:
  directories:
    - $HOME/.composer/cache

addons:
  chrome: stable

services:
  - mysql

before_install:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE homestead;'

install:
  - if [[ $SETUP = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - php artisan migrate

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - composer check-style
  - composer test
