dist: xenial
language: php

env:
  global:
    - APP_ENV=testing
    - APP_DEBUG=false
    - APP_KEY=01234567890123456789012346579012
    - APP_URL=http://127.0.0.1:8000
    - DB_CONNECTION=mysql
    - DB_HOST=127.0.0.1
    - DB_PORT=3306
    - DB_DATABASE=homestead
    - DB_USERNAME=travis
    - DB_PASSWORD=
    - LOG_CHANNEL=single
    - BUGSNAG_API_KEY=

matrix:
  fast_finish: true
  include:
    - php: 7.4

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/yarn/v4

addons:
  chrome: stable

services:
  - mysql

before_install:
  - sudo apt-get install -y php-common
  - travis_retry composer self-update
  - mysql -e 'CREATE DATABASE homestead;'
  - nvm install --lts

install:
  - travis_retry composer install
  - php artisan migrate
  - php artisan dusk:chrome-driver
  - yarn
  - yarn run prod

before_script:
  - echo 'xdebug.max_nesting_level = 1024' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - vendor/bin/phpcs --standard=ruleset.xml
  - vendor/bin/psalm --show-info=false
  - vendor/bin/phpunit --verbose --configuration phpunit.xml --testsuite Unit --coverage-clover coverage.clover
  - vendor/bin/phpunit --verbose --configuration phpunit.xml --testsuite Feature --no-coverage
  - php artisan dusk
  - phpdismod -s cli xdebug &&
    vendor/bin/deptrac &&
    phpenmod -s cli xdebug;

after_script:
  - |
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
